### ISSUE TITLE
Related package: fledge

### ISSUE THREAD

**Issue by maelle** [kapsner/autonewsmd#3]
:wave: @kapsner! I discovered your package thanks to R Weekly. Very cool! :smile_cat: 

@krlmlr and others including myself have been working on a package called [fledge](https://cynkra.github.io/fledge/dev/) that also helps streamline the changelog generation as well as the version bumping & git tag creation. It currently has some limited support for conventional commits, with [more planned](https://github.com/cynkra/fledge/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22conventional+commits+%3Asparkles%3A%22).

Maybe both packages could cross-reference each other, or even collaborate? In any case good luck with further development of autonewsmd!

**Comment by kapsner** [comment]
Hi @maelle ,

Thank you very much for your feedback and your note regarding the `fledge` package. My bad that I did not discover your package before writing this one.

Thanks for the suggestion to add a cross-reference to `fledge` - there is now a new section on "Related R Packages" included into the readme: https://github.com/kapsner/autonewsmd/tree/development#related-r-packages

Good to hear that you are planning to extend the support for conventional commits in your package. `autonewsmd` also does not yet fully support them with some of the major TODOs listed [here](https://github.com/kapsner/autonewsmd/tree/development#todos).

I am also open for collaboration - how would you imagine that?

**Comment by krlmlr** [comment]
Thanks! Adding @Dschaykib, author of {newsmd}.

We should add a similar section to fledge's README.

One thing that fledge currently lacks is an object to define the contents of `NEWS.md` . Automatic generation of the NEWS worked well so far without it, now we need this for various (more or less advanced) operations. This is what both {newsmd} and {autonewsmd} provide, independently as it seems.

I wonder if a "plain old object", aka list with a `"class"` attribute, could do here too. "Methods" would be plain functions that return a modified copy of the object. This seems a bit more idiomatic to me, I try to avoid implicit state whenever possible. What methods are useful on such an object?

I'm not super familiar with conventional commits, it would be great to double-check if our idea matches the way people tend to use it.

What should we have done to make this package easier to discover?

Are there features you'd like to see in fledge?

**Comment by Dschaykib** [comment]
Hey,
I added a reference at the newsmd dev branch :) (see [here](https://github.com/Dschaykib/newsmd/commit/face5dd137764638131909a1c36f24a8d950c873))

@krlmlr in the end, if it is an R6 object or function used on a list... it's all the same. I preferred the R6 in this case since typically there is only one news.md file and I thought it would be easier if the object representing this file would be handled like within the [desc package](https://github.com/r-lib/desc) (that's where I got my idea from).

Also the newsmd handles the input quite plainly, "first come first serve" so to speak. Meaning: at the moment I just use a vector with all inputs combined together. To improve this, each "version" could be an entry in a list, which are then concatenated. With this, it would be possible to add inputs later or at a specific position.

**Comment by kapsner** [comment]
@krlmlr yes, `autonewsmd` first generates a list with the tags being the items of the first list-level, containing the information on all related commits. Rendering the changelog file then consists basically of looping over this list to include the information of each list-item into the respective sub-section of the changelog.

I was originally using the python package [auto-changelog](https://github.com/KeNaCo/auto-changelog) to create the changelogs of my R projects that rely on conventional commits (see for example [here](https://github.com/miracum/dqa-dqastats/blob/e469966750c3a3598248662e85767c7c3d9f6f72/data-raw/devstuffs.R#L167)). However, due to some dependency issues, there were errors when using the `auto-changelog` version from pip and a PR addressing these issues [remained unanswered so far](https://github.com/KeNaCo/auto-changelog/pull/114), so it seemed as if, unfortunatelly, this software is not actively maintained anymore.... this was when I started looking for alternatives.

> What should we have done to make this package easier to discover?

I remember that I indeed stumbled upon [`fledge`'s vignette](https://cran.r-project.org/web/packages/fledge/vignettes/demo.html) when searching for a solution in R. I would suggest to start this vignette with one sentence regarding the purpose of the R package and to explicitly mention the term "conventional commits" in this vignette as well (I discovered yesterday that this term is mentioned in [`fledge`'s readme](https://github.com/cynkra/fledge#fledge), which I did not discover in the google-search). When initially reading this vignette, I came to the decision that `fledge` seems to be beyond the scope of my intention, which was to generate a changelog only with conventional commits without even allowing to include anything else manually.

And I think this is one major distinction between the both packages `newsmd` and `fledge`, which update pre-existing changelog files, and `autonewsmd`, which generates a new changelog file and overwrites the pre-existing file. When relying on conventional commits, this leads basically to the same result as updating the file, however, pre-existing entries in the changelog file that do not follow the convention would be lost when using `autonewsmd`.

> I'm not super familiar with conventional commits, it would be great to double-check if our idea matches the way people tend to use it.

Right - what I did during development is to search for publicly available git repos (not only R-projects) that already rely on conventional commits and to re-generate their changelog using `autonewsmd` and compare the results.

Another thought on the R object used to generate the changelog file: as mentioned above, for `autonewsmd` this is currently a list with the tags as the list-items, corresponding to the subheadings of the changelog file. One could imagine, that some projects would like to have some different layout of their changelog and this is why `autonewsmd` uses [markdown templates](https://github.com/kapsner/autonewsmd/blob/main/inst/templates/news-md-template.Rmd) (currently only the one that sorts commits by tags). My plan is to provide some more templates in the future (e.g. sorting by commit-type etc.) and just adapt the logic to extract the information from the generated list with all commits.
To keep the package as minimal as possible and to have all configuration options in one place, I decided to go with R6 instead of having one or two functions with lots of arguments to configure the changelog.

@Dschaykib thanks for adding the related packages to your readme 🎉
